codeunia-dev/codeunia

app/admin/users/page.tsx
components/admin/Sidebar.tsx

Add background pattern to UsersPage and highlight active sidebar item

Add background pattern to UsersPage and highlight active sidebar item

---

app/admin/blog-posts/page.tsx
components/ui/alert.tsx

Added blog management feature for admin

Added blog feature for admin

---

app/auth/signin/page.tsx
app/auth/signup/page.tsx
app/protected/page.tsx
components/home/LatestContentPreview.tsx

Refactor SignIn and SignUp forms to include rounded corners for improved aesthetics; add navigation link to ProtectedPage for better user experience; enhance LatestContentPreview buttons for a modern look.

Refactor SignIn and SignUp forms to include rounded corners

---

components/admin/Sidebar.tsx

Update Sidebar component to apply a black background to SidebarInset for improved UI consistency

Update Sidebar component to apply a black background to SidebarInset for improved UI consistency

---

app/join/sponsorship/page.tsx
components/forms/mentor-form.tsx
components/forms/sponsorship-form.tsx

Added Sponsorship Form and updated label in MentorForm from "Current Position" to "Current Role"

Added Sponsorship Form and updated label in MentorForm from "Current Position" to "Current Role"

---

app/join/collaboration/page.tsx
app/join/page.tsx
components/forms/collaboration-form.tsx

Added collaboration page and form ,also renamed the partnership on the join page to collaboration page

Added collaboration page

---

app/about/page.tsx
app/auth/signin/page.tsx
app/auth/signup/page.tsx
app/protected/page.tsx
components/home/HeroSection2.tsx
components/ui/typewriter-effect.tsx
components/user-icon.tsx

Refactor: Replace Typewriter component with TypewriterEffect in SignIn and SignUp forms, update About page testimonials, Remove Protected Area from user dashboard, adjust UserIcon size and renamed Next gen coding community to Fueling Devs. Driving Ideas.

Ui enhancements 

---

app/auth/callback/page.tsx
app/auth/confirm/route.ts
app/auth/signin/page.tsx
app/auth/signup/page.tsx
app/protected/page.tsx
lib/supabase/middleware.ts

Enhancement: Implement OAuth sign-in with Google in SignIn and SignUp

---

app/auth/callback/page.tsx
app/auth/signin/page.tsx

Update returnUrl handling in OAuth callback and SignIn form

Refactor: Update returnUrl handling in OAuth callback and SignIn form

---

app/admin/page.tsx
app/admin/users/page.tsx

Enhancement: Integrate total users count and trend analysis in Admindashboard, fetching data from API and updating UI accordingly also fix the avatar problem in users page

Enhancement: Integrate total users count and trend analysis in Admindashboard

---

app/admin/forms/volunteer/page.tsx
app/api/admin-volunteers/route.ts

Implemented AdminVolunteerPage, a Next.js client-side component for managing volunteer applications. Features include data fetching from /api/admin-volunteers, search and status filtering, responsive table display, stats cards, and actions to view, approve, reject, or delete applications. Uses Tailwind CSS, custom UI components, and sonner for toast notifications.

Feature: Add new page for Volunteer Applications

---

app/admin/forms/judges/page.tsx
app/api/admin-judges/route.ts

Feature: Implement Volunteer Applications page with form submission functionality

Feature: Implement Volunteer Applications page with form submission 

---

app/admin/forms/mentor/page.tsx
app/api/admin-mentors/route.ts

Implement Mentor Applications page with form submission functionality

Feature: Implement Mentor Applications page with form submission functionality

---

app/admin/forms/sponsorship/page.tsx
app/api/admin-sponsorship/route.ts
components/forms/sponsorship-form.tsx

Implement Sponsorship Applications page with form submission functionality also fixed the staus field in the sponsorship form component

Feature: Implement Sponsorship Applications page with form submission functionality

---

app/admin/forms/collaboration/page.tsx
app/api/admin-collaboration/route.ts

Enhance Collaboration Applications page with validation and error handling for form submissions

Feature: Enhance Collaboration Applications page with validation and error handling for form submissions

---

app/admin/blog-posts/page.tsx

Add image upload functionality to Blog Post form with auto-insert html tag

Feature: Add image upload functionality to Blog Post form 

---

app/api/blog/[slug]/like/route.ts
app/blog/[slug]/page.tsx

Add like button functionality to blog posts with tooltip support

Feature: Add like button functionality to blog posts with tooltip support

---

app/blog/[slug]/page.tsx
components/ui/share-button.tsx

This PR integrates the `ShareButton` component into individual blog post pages to enable easy content sharing across platforms.

Feature: Integrate ShareButton component into blog post pages for enhanced sharing functionality

---

app/about/page.tsx
app/contact/page.tsx

Revamp About and Contact pages with enhanced UI elements and improved call-to-action buttons

Feature: Revamp About and Contact pages with enhanced UI elements and improved call-to-action buttons

---

app/blog/[slug]/page.tsx

Refactor BlogPostPage for article image responsiveness

Feature: Refactor BlogPostPage for article image responsiveness

---

app/admin/blog-posts/page.tsx

Refactor BlogPost functionality to calculate likes from blog_likes table and update BlogFormData structure

Refactor BlogPost functionality to calculate likes from blog_likes 

---

app/auth/signin/page.tsx
app/auth/signup/page.tsx

Add GitHub OAuth sign-in functionality to SignInForm and SignUpForm . Implement loading state and error handling for sign-in process.

Add GitHub OAuth sign-in functionality to SignInForm and SignUpForm

---

app/contact/page.tsx

Fix typo in ContactPage component: update "CodeUnia" to "Codeunia" for consistency.

Fix typo in ContactPage component: update "CodeUnia" to "Codeunia" 

---

app/about/page.tsx
app/join/page.tsx
components/home/HeroSection2.tsx

Update statistics in About and Join pages, and adjust values in HeroSection component for consistency

Update statistics in About and Join pages, and adjust values in HeroSection

---

app/about/components/SponsorsSection.tsx
app/about/components/TeamSection.tsx
app/blog/page.tsx
app/contact/page.tsx

Update SponsorsSection to adjust layout for sponsors and enhance styling for Innovxus. Remove Nidhi Gupta from TeamSection. Modify button cursor styles in BlogPage and ContactPage for consistency.

Update SponsorsSection to adjust layout for sponsors and enhance styling

---

app/about/page.tsx

Implement user authentication and dynamic call-to-action sections in AboutPage. Enhance loading state handling and personalize messages for logged-in users, while providing options for new users to join the community.

Implement user authentication and dynamic call-to-action sections in 

---

app/admin/layout.tsx
app/api/hackathons/[slug]/route.ts
app/api/hackathons/featured/route.ts
app/api/hackathons/route.ts
app/hackathons/[id]/page.tsx
app/hackathons/page.tsx
app/opportunities/page.tsx
components/header.tsx
hooks/useHackathons.ts
lib/services/hackathons.ts

- Implemented OpportunitiesPage component with a hero section and grid layout for various opportunities.
- Created a new hook useHackathons for fetching hackathon data with search and filter capabilities.
- Developed a service hackathonsService for server-side operations related to hackathons, including fetching, creating, updating, and deleting hackathons.
- Added types and interfaces for hackathon data structures and responses.

feat: add opportunities page with hackathons, events, projects, and jobs sections

---

app/admin/hackathons/page.tsx
lib/services/hackathons.ts

Enhance Admin Hackathons: Add new fields for organizer contact, eventdetails and update status options

Enhance Admin Hackathons: Add new fields for organizer contact, eventdetails

---

app/admin/hackathons/page.tsx

Refactor Admin Hackathons: Remove unused social fields and update status options

Refactor Admin Hackathons: Remove unused social fields and update status options

---

app/admin/hackathons/page.tsx
lib/services/hackathons.ts

Refactor Admin Hackathons: Change schedule and FAQ fields to arrays for better data handling and update form submission logic accordingly

Refactor Admin Hackathons: Change schedule and FAQ fields to 

---

components/home/LatestContentPreview.tsx

Refactor LatestContentPreview: Add hackathon fetching logic, update UI to display upcoming hackathons, and enhance related components.

Refactor LatestContentPreview: Add hackathon fetching logic, update UI

---

app/protected/profile/page.tsx
app/protected/profile/view.tsx
app/protected/profile/view/page.tsx
components/ui/avatar.tsx
components/users/ProfileView.tsx
components/users/StudentSidebar.tsx
package-lock.json
package.json

feat: implement profile view and enhance profile page with new components

feat: implement profile view and enhance profile page with new components

---

app/verify/[memberId]/page.tsx
components/MembershipCard.tsx
lib/supabase.ts
package-lock.json
package.json

add QR code verification to MembershipCard and implement member verification page

feat: add QR code verification to MembershipCard 

---

app/[username]/page.tsx
app/about/page.tsx
app/hackathons/[id]/page.tsx

remove unused Card import from about page
simplify catch blocks by removing unused error parameter replace apostrophes with HTML entities in text content

refactor: clean up unused imports and improve error handling

---

app/admin/certificates/page-simple.tsx
app/admin/certificates/page.tsx
app/api/admin/certificates/data/route.ts
app/api/admin/certificates/participants/route.ts
app/api/admin/check-status/route.ts
app/api/auth/user/route.ts
app/api/certificates/bulk-generate/route.ts
app/api/certificates/generate/route.ts
app/auth/confirm/route.ts
app/auth/signup/page.tsx
app/tests/[id]/leaderboard/page.tsx
app/tests/[id]/page.tsx
app/tests/[id]/results/page.tsx
app/tests/page.tsx
components/CookieConsentBanner.tsx
components/ReactDevTools.tsx

- Remove unused imports across multiple files
- Add proper type interfaces for state variables
- Remove unused variables and simplify logic
- Improve error handling by removing unnecessary error logging

refactor: clean up unused imports and improve type safety

---

app/admin/reserved-usernames/page.tsx
app/api/admin/certificates/participants/route.ts
app/auth/email-confirmation-required/page.tsx
app/setup/page.tsx
components/CertificateGenerator.tsx
components/header.tsx
components/ui/animated-testimonials.tsx
lib/auth/admin-auth.ts
lib/supabase/test-connection.ts

fix: replace apostrophes with HTML entities in strings
perf: improve useEffect dependencies with useCallback
style: replace img with Next.js Image component
fix: add proper type annotations for better type safety

refactor: optimize code by removing unused imports and variables

---

app/api/admin/certificates/save/route.ts
app/api/admin/pending-payments/route.ts
app/api/admin/tests/[id]/route.ts
app/api/admin/tests/route.ts
app/api/hackathons/featured/route.ts
app/api/hackathons/route.ts
package-lock.json

- Add interface definitions for API request/response types
- Replace 'any' types with proper type interfaces
- Use nullish coalescing operator for default values
- Improve code consistency and maintainability

refactor(api): add type definitions and improve type safety

---

app/premium/page.tsx
app/tests/[id]/take/page.tsx
components/ProductionCacheExample.tsx
components/RoundsDisplay.tsx
components/UsernameField.tsx
components/admin/RoundsManager.tsx
components/auth-debug.tsx
components/ui/vortex.tsx
lib/dynamic-imports.ts
lib/services/activity.ts
lib/services/hackathons.ts

- Replace 'any' with proper types in multiple components
- Remove unused imports and variables
- Use useCallback for memoizing functions
- Update type definitions for better type safety

refactor: improve type safety and remove unused dependencies

---

components/CodeuniaCookieSystem.tsx
components/ProductionCacheExample.tsx
components/admin/RoundsManager.tsx

- Add proper type definitions for LeaderboardEntry in ProductionCacheExample
- Replace 'any' with specific types in RoundsManager updateRound function
- Add proper type interfaces for analytics and activity summaries in CodeuniaCookieSystem
- Replace 'any' with union types and type guards for better type safety

refactor: improve type safety in multiple components

---

components/admin/TestManager.tsx

- Add strongly typed interfaces for API responses and component state
- Replace 'any' types with proper TypeScript interfaces
- Organize type definitions at the top of the file
- Use useCallback for memoizing fetch functions
- Improve error handling with proper type checking

refactor(test-management): improve type safety and code organization in TestManager

---

components/users/StudentSidebar.tsx

Main Changes:
Created a Fixed Mobile Header Bar: Instead of just having a floating button, I created a full-width fixed header bar at the top for mobile devices that contains:
The menu button (Sheet trigger)
A mini logo/brand display for better mobile UX

Fixed sidebar with a non scrolling menu button

---

app/protected/internships/page.tsx

- fix the primary key to use combination of email,domain and start_date

style(internships): increase max width of page container from 4xl to 7xl

---

components/MembershipCard.tsx
components/codeunia-logo.tsx

- Replace PdfLogo with CodeuniaLogo for consistency
- Increase PDF dimensions and adjust layout to match visible card
- Add unique gradient IDs to prevent SVG conflicts
- Enhance card styling and member information display

feat(MembershipCard): improve PDF generation and card design

---

app/tests/[id]/take/page.tsx

fix(tests): conditionally render footer to avoid overlap in fullscreen mode 

---

app/about/page.tsx
app/admin/certificates/page-simple.tsx
app/admin/certificates/page.tsx
app/admin/events/page.tsx
app/admin/forms/collaboration/page.tsx
app/admin/forms/judges/page.tsx
app/admin/forms/mentor/page.tsx
app/admin/forms/sponsorship/page.tsx
app/admin/forms/volunteer/page.tsx
app/admin/hackathons/page.tsx
app/admin/internship-applications/page.tsx
app/admin/pending-payments/page.tsx
app/internship/page.tsx
app/page.tsx
app/premium/page.tsx
components/CertificateGenerator.tsx
components/RoundsDisplay.tsx
components/admin/TestManager.tsx
components/home/HeroSection2.tsx
dev.log
lib/api-fetch.ts

- Remove birthday celebration modal from homepage for better UX
- Add new API fetch utility for centralized request handling
- Update multiple admin pages with improved functionality
- Enhance certificate generation components
- Optimize homepage components and reduce bundle size
- Add development logging for better debugging
- Update forms and admin interfaces with better error handling
- Improve overall application performance and user experience

feat: Remove birthday celebration dialog and improve performance

---

app/api/email-preview/internship/route.ts
app/api/internships/apply/route.ts
lib/services/email.ts
package-lock.json

Added internship mailing function

Added Internship mailing function

---

lib/pdf-generator.ts

Attempt 02 for fixing the internship pdf content

Attempt 02 for fixing the internship pdf content

---

components/users/StudentSidebar.tsx

implement toggle button to collapse/expand sidebar adjust layout and styling for collapsed state
add transition animations for smooth resizing

feat(StudentSidebar): add collapsible sidebar functionality

---

components/ai/AIChat.tsx

Improve layout by centering the logo horizontally in the auth section of AIChat component

refactor(components): wrap CodeuniaLogo in flex container for better centering

---

app/projects/page.tsx
app/projects/projects.json
components/header.tsx

- Create new projects page with card-based layout
- Add projects data from JSON file
- Include navigation link in header

feat(projects): add projects showcase page with intern projects data

---

app/projects/page.tsx
app/projects/projects.json

Centralize project metadata in projects.json for better maintainability and single source of truth

refactor(projects): move project descriptions and tags to projects.json

---

.github/workflows/ci-cd.yml

- Updated CodeQL actions from v2 to v3 to fix deprecation warnings
- Updated Node.js version from 18 to 20 to fix engine compatibility warnings
- Added security-events:write permission for CodeQL to upload results
- Added contents:read and actions:read permissions for proper workflow execution

FIX: Update CodeQL to v3, Node.js to v20, and add security permissions
